'use strict';
const path=require('path');
const {jidNumber,isGroupJid}=require('../lib/helpers');
const names=['ping','menu','groupinfo','vv','sticker','play','video','lyrics','tagall','tagadmin','add','kick','promote','demote','mute','anti'];
const commands=new Map();
for(const name of names){const loaded=require(path.join(__dirname,name));for(const command of (Array.isArray(loaded)?loaded:[loaded])){if(!command?.name||typeof command.run!=='function')continue;commands.set(String(command.name).toLowerCase(),command);for(const a of command.aliases||[])commands.set(String(a).toLowerCase(),command);}}
function getText(message){const m=message?.message||{};if(m.conversation)return String(m.conversation).trim();if(m.extendedTextMessage?.text)return String(m.extendedTextMessage.text).trim();if(m.imageMessage?.caption)return String(m.imageMessage.caption).trim();if(m.videoMessage?.caption)return String(m.videoMessage.caption).trim();return '';}
function parse(text){const s=String(text||'').trim();if(!s.startsWith('.'))return null;const p=s.slice(1).trim().split(/\s+/);const name=(p.shift()||'').toLowerCase();return name?{name,args:p}:null;}
function mentions(message){const c=message?.message?.extendedTextMessage?.contextInfo||message?.message?.imageMessage?.contextInfo||message?.message?.videoMessage?.contextInfo||message?.message?.documentMessage?.contextInfo||{};return Array.isArray(c.mentionedJid)?c.mentionedJid:[];}
async function group(ctx){if(!isGroupJid(ctx.remoteJid))throw new Error('This command only works in groups.');const metadata=await ctx.socket.groupMetadata(ctx.remoteJid);const botJid=ctx.socket?.user?.id||'';const senderJid=ctx.senderJid||'';const participants=metadata.participants||[];const bot=participants.find(p=>jidNumber(p.id)===jidNumber(botJid));const sender=participants.find(p=>jidNumber(p.id)===jidNumber(senderJid));return {metadata,participants,botJid,botIsAdmin:Boolean(bot?.admin),senderJid,senderIsAdmin:Boolean(sender?.admin),isGroup:true};}
async function handleWhatsAppCommand(userId,session,message){if(!session?.socket)return false;const text=getText(message);const parsed=parse(text);if(!parsed)return false;const command=commands.get(parsed.name);if(!command)return false;const remoteJid=message?.key?.remoteJid;if(!remoteJid)return false;const senderJid=message?.key?.participant||message?.key?.remoteJid||session.socket?.user?.id||'';const ctx={userId:String(userId),session,socket:session.socket,message,remoteJid,text,command:parsed.name,args:parsed.args,mentions:mentions(message),senderJid,isSelf:message?.key?.fromMe===true,isGroup:isGroupJid(remoteJid),group};ctx.reply=async(content,options={})=>session.socket.sendMessage(remoteJid,typeof content==='string'?{text:content}:content,options);ctx.textReply=async(value,options={})=>session.socket.sendMessage(remoteJid,{text:String(value)},options);await command.run(ctx);return true;}
global.handleWhatsAppCommand=handleWhatsAppCommand;
module.exports={commands,handleWhatsAppCommand,getText,parse};
