'use strict';
const {sleep}=require('../lib/helpers');
const {createWhatsAppSession,getWhatsAppSession,getPairingState,completelyResetUser}=require('../lib/whatsapp');
const WAITING_TIMEOUT=5*60*1000;const PAIRING_CODE_TIMEOUT=90*1000;
function states(){global.pairingStates ||= {};return global.pairingStates;}
function getState(id){return states()[String(id)]||null;}
function setState(id,data){const k=String(id);states()[k]={...(states()[k]||{}),...data,updatedAt:Date.now()};return states()[k];}
function clearState(id){const k=String(id),s=states()[k];if(s?.timeout)clearTimeout(s.timeout);delete states()[k];}
function refresh(ctx,id){const k=String(id),s=getState(k);if(!s)return;if(s.timeout)clearTimeout(s.timeout);s.timeout=setTimeout(async()=>{if(!getState(k))return;try{await completelyResetUser(k);}catch(e){console.error('[PAIR TIMEOUT]',e);}try{await ctx.reply('⏰ Pairing timed out. Use /pair to try again.');}catch{}clearState(k);},WAITING_TIMEOUT);}
function normalizePhoneNumber(input){let v=String(input||'').trim().replace(/[^\d+]/g,'');if(v.startsWith('00'))v='+'+v.slice(2);if(v.startsWith('0')&&!v.startsWith('00'))v='+234'+v.slice(1);v=v.replace(/\D/g,'');return v.length>=10&&v.length<=15?v:null;}
async function beginPairing(ctx){const id=ctx.from?.id;if(!id)return;const k=String(id);if(getState(k))return ctx.reply('⚠️ A pairing request is already active. Send the number or /cancel.');setState(k,{status:'waiting_number',phoneNumber:null,pairingCode:null,createdAt:Date.now(),chatId:ctx.chat?.id});await ctx.reply('🔄 Send your WhatsApp number with country code.\n\nExample: `2348012345678`\nNigerian local numbers such as `08012345678` are also accepted.\n\nUse /cancel to stop.',{parse_mode:'Markdown'});refresh(ctx,k);}
async function handlePairNumber(ctx){const id=ctx.from?.id;if(!id||!ctx.message?.text)return;const k=String(id),s=getState(k);if(!s||s.status!=='waiting_number')return;const phone=normalizePhoneNumber(ctx.message.text);if(!phone)return ctx.reply('❌ Invalid number. Example: `2348012345678`',{parse_mode:'Markdown'});setState(k,{status:'creating_session',phoneNumber:phone,chatId:ctx.chat?.id});refresh(ctx,k);try{await ctx.reply(`🔄 Starting WhatsApp pairing for +${phone}...`);const result=await createWhatsAppSession(k,phone,{fresh:true});const ps=getPairingState(k);if(ps)ps.chatId=ctx.chat?.id;setState(k,{status:'waiting_code'});let code=result?.pairingCode;for(let i=0;!code&&i<180;i++){code=getWhatsAppSession(k)?.pairingCode||getPairingState(k)?.pairingCode;await sleep(500);}if(!code)throw new Error('WhatsApp did not provide a pairing code in time.');setState(k,{status:'waiting_connection',pairingCode:code});await ctx.reply(`🔐 WHATSAPP PAIRING CODE\n\n*${code}*\n\nWhatsApp → Settings → Linked devices → Link a device → Link with phone number instead → enter the code.\n\n⏳ Waiting for connection...`,{parse_mode:'Markdown'});refresh(ctx,k);}catch(e){console.error(`[PAIR] ${k}:`,e?.stack||e);try{await completelyResetUser(k);}catch{}clearState(k);await ctx.reply(`❌ Pairing failed. ${e?.message||'Try again with /pair.'}`);}}
async function cancelPairing(ctx){const id=ctx.from?.id;if(!id)return;const k=String(id);if(!getState(k))return ctx.reply('ℹ️ No active pairing request.');try{await completelyResetUser(k);}catch{}clearState(k);await ctx.reply('🛑 Pairing cancelled and saved WhatsApp authentication removed. Use /pair to start again.');}
function getPairingStatus(id){const s=getState(id);return s?{status:s.status,phoneNumber:s.phoneNumber,pairingCode:s.pairingCode,createdAt:s.createdAt,updatedAt:s.updatedAt}:null;}
module.exports={beginPairing,handlePairNumber,cancelPairing,getPairingStatus,normalizePhoneNumber};
