'use strict';
const {sleep}=require('../lib/helpers');
const {createWhatsAppSession,getWhatsAppSession,getPairingState,completelyResetUser}=require('../lib/whatsapp');
const STATES=global.telegramPairingStates ||= {};
const TIMEOUT=10*60*1000;
function getState(id){return STATES[String(id)]||null;}
function setState(id,data){const k=String(id);STATES[k]={...(STATES[k]||{}),...data,updatedAt:Date.now()};return STATES[k];}
function clearState(id){const k=String(id),s=STATES[k];if(s?.timeout)clearTimeout(s.timeout);delete STATES[k];}
function refresh(ctx,id){const k=String(id),s=getState(k);if(!s)return;if(s.timeout)clearTimeout(s.timeout);s.timeout=setTimeout(async()=>{const current=getState(k);if(!current)return;const wa=getWhatsAppSession(k);if(wa?.connected){clearState(k);return;}try{await completelyResetUser(k);}catch(e){console.error('[PAIR TIMEOUT]',e?.message||e);}clearState(k);try{await ctx.reply('⏰ Pairing request expired. Use /pair to start a new one.');}catch{}},TIMEOUT);}
function normalizePhoneNumber(input){let v=String(input||'').trim().replace(/[^\d+]/g,'');if(v.startsWith('00'))v='+'+v.slice(2);if(v.startsWith('0')&&!v.startsWith('00'))v='+234'+v.slice(1);v=v.replace(/\D/g,'');return v.length>=10&&v.length<=15?v:null;}
async function beginPairing(ctx){const id=ctx.from?.id;if(!id)return;const k=String(id);if(getState(k))return ctx.reply('⚠️ A pairing request is already active. Send the WhatsApp number or use /cancel.');setState(k,{status:'waiting_number',phoneNumber:null,pairingCode:null,chatId:ctx.chat?.id});await ctx.reply('🔄 WhatsApp pairing\n\nSend your WhatsApp number with country code.\n\nExample: `2348012345678`\nLocal Nigerian numbers such as `08012345678` are also accepted.\n\nUse /cancel to stop.',{parse_mode:'Markdown'});refresh(ctx,k);}
async function handlePairNumber(ctx){const id=ctx.from?.id;if(!id||!ctx.message?.text)return;const k=String(id),st=getState(k);if(!st||st.status!=='waiting_number')return;const phone=normalizePhoneNumber(ctx.message.text);if(!phone)return ctx.reply('❌ Invalid number. Example: `2348012345678`',{parse_mode:'Markdown'});setState(k,{status:'creating_session',phoneNumber:phone,chatId:ctx.chat?.id});refresh(ctx,k);try{await ctx.reply(`🔄 Starting WhatsApp pairing for +${phone}...\n\nPlease keep WhatsApp open while linking.`);const result=await createWhatsAppSession(k,phone,{fresh:true,chatId:ctx.chat?.id});const p=getPairingState(k);if(p)p.chatId=ctx.chat?.id;const code=result?.pairingCode||p?.pairingCode;if(!code)throw new Error('WhatsApp did not provide a pairing code.');setState(k,{status:'waiting_connection',pairingCode:code});await ctx.reply(`🔐 WhatsApp pairing code\n\n*${code}*\n\nOn WhatsApp: Settings → Linked devices → Link a device → Link with phone number instead → enter this code.\n\n⏳ Waiting for WhatsApp to confirm the connection.`,{parse_mode:'Markdown'});refresh(ctx,k);}catch(e){console.error(`[PAIR] ${k}:`,e?.stack||e);try{await completelyResetUser(k);}catch{}clearState(k);await ctx.reply(`❌ Pairing failed. ${e?.message||'Please try /pair again.'}`);}}
async function cancelPairing(ctx){const id=ctx.from?.id;if(!id)return;const k=String(id);if(!getState(k))return ctx.reply('ℹ️ No active pairing request.');try{await completelyResetUser(k);}catch{}clearState(k);await ctx.reply('🛑 Pairing cancelled and WhatsApp authentication removed. Use /pair to start again.');}
function getPairingStatus(id){const s=getState(id);return s?{status:s.status,phoneNumber:s.phoneNumber,pairingCode:s.pairingCode,createdAt:s.createdAt,updatedAt:s.updatedAt}:null;}
module.exports={beginPairing,handlePairNumber,cancelPairing,getPairingStatus,normalizePhoneNumber};
